global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'movie-app'
    static_configs:
      - targets: ['movie-app:8080']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scheme: http